### PR TITLE
Bug fixes

### LINKED ISSUE #249: LOGIN_ERROR isn't set, as getRequestInfo doesn't set the requestType correctly
When there is an invalid_state error, the getRequestInfo  fails to set the requestType as the the state doesn't match.
The requestType valu is set only when there is a match, and is taken from the sessionStorage.

You should get the request type from the returned state parameter in the hash.

### PR DESCRIPTION
**Pull request by tushargupta51**
#249 #247 : broadcasting 'adal:stateMismatch' error whenever invalid state is received.
#212 : updating the 'license' field in package.json
#180 : added adal library version in log messages, each message will contain the version, we can consider adding only once but it does not matter so much, method returns a constant and its not going to clutter messages.
#111 : whenever interceptor rejects a request because a login is in progress, adal broadcase 'adal:errorResponse' with the rejection message, this event will be raised if some other error happened (except 401 for which there is a different event) when interceptor processing the request.
#76 : we maintain a flag adal._renewActive, if the flag is set, we do not initiate another login request while a renew request is in progress.

Other then the above bugs:
1. Removed state.idToken and failed.renew storage constants since they are redundant and are not needed. we do not try to acquire token again if the previous request failed for some reason, this does not look correct behavior to me. In case of failure, we do send the error to the registered callback.
2. Added tests
3. Cleanup

@polita @brentschmaltz @weijjia

### CODE REVIEW

File: lib/adal.js [hunk 1]
```diff
@@ -176,11 +171,10 @@ AuthenticationContext.prototype.login = function () {
     this._saveItem(this.CONSTANTS.STORAGE.LOGIN_ERROR, '');
     this._saveItem(this.CONSTANTS.STORAGE.STATE_LOGIN, expectedState);
     this._saveItem(this.CONSTANTS.STORAGE.NONCE_IDTOKEN, this._idTokenNonce);
-    this._saveItem(this.CONSTANTS.STORAGE.FAILED_RENEW, '');
     this._saveItem(this.CONSTANTS.STORAGE.ERROR, '');
     this._saveItem(this.CONSTANTS.STORAGE.ERROR_DESCRIPTION, '');
-    
-    
+
+
```
Comment (weijjia) [inline lib/adal.js]: nit: extra line

File: lib/adal.js [hunk 2]
```diff
@@ -1187,7 +1141,7 @@ AuthenticationContext.prototype._cloneConfig = function (obj) {
     return copy;
 };
 
-AuthenticationContext.prototype._addClientId = function () {
+AuthenticationContext.prototype._addXClientParameters = function () {
```
Comment (weijjia) [inline lib/adal.js]: the name is not so clear, we're actually adding lib version.

File: package.json [hunk 3]
```diff
@@ -5,15 +5,10 @@
...
-      "url": "http://www.apache.org/licenses/LICENSE-2.0"
-    }
-  ],
+  "license": "Apache-2.0",
   "repository": {
     "type": "git",
-    "url": ""
+    "url": "https://github.com/AzureAD/azure-activedirectory-library-for-js.git"
   },
   "version": "1.0.8",
```
Comment (weijjia) [inline package.json]: this version should also be updated if you're going to change the version to 1.0.9

File: lib/adal.js [hunk 4]
```diff
@@ -709,28 +672,28 @@ AuthenticationContext.prototype.saveTokenFromHash = function (requestInfo) {
...
-            
+
             var keys, resource;
-            
+
             if (requestInfo.parameters.hasOwnProperty(this.CONSTANTS.ACCESS_TOKEN)) {
                 this.info('Fragment has access token');
                 // default resource
                 resource = this.config.loginResource;
+                if (requestInfo.requestType === this.REQUEST_TYPE.RENEW_TOKEN) {
```
Comment (weijjia) [inline lib/adal.js]: I'm thinking why we have this check here? if the fragment has access token, it can only be renew token request. If so, we should always be able tell the resource based on state response, then why setting the default resource?

**Comment by weijjia** [comment]
For the broadcasting error message, as long as everybody agrees on it, then we should be good. If we start broadcasting those errors at the angular level, developer would rely on them, then we need to be cautions when changing them.

File: lib/adal.js (hunk 4 above)
Comment (tushargupta51) [inline lib/adal.js]: You are correct. I don't think resource = this.config.loginResource is needed.

File: lib/adal.js (hunk 2 above)
Comment (tushargupta51) [inline lib/adal.js]: we are adding x-client-SKU and x-client-ver parameters, thats why named it addXClientParameters.

Comment (weijjia) [inline lib/adal.js]: oh, sorry, i miss the x-client-sku. XClientParmeters is still not so clear to me, I have to look into the method for what it is adding.

File: package.json (hunk 3 above)
Comment (tushargupta51) [inline package.json]: thanks for this, updated the version at other places too.

File: lib/adal.js (hunk 2 above)
Comment (tushargupta51) [inline lib/adal.js]: Since both of these values represent information about the library, sku==platform, ver==version, another names could be _addLibraryMetadata or _addMetadata.

Comment (weijjia) [inline lib/adal.js]: i vote for  _addLibraryMetadata

File: lib/adal-angular.js [hunk 5]
```diff
@@ -89,6 +89,7 @@ if (typeof module !== 'undefined' && module.exports) {
                         }
 
                         if (requestInfo.requestType !== _adal.REQUEST_TYPE.LOGIN) {
+                            _adal._renewActive = false;
```
Comment (ischrei) [inline lib/adal-angular.js]: Sorry I'm putting the comment in a wrong line - I think we should add a broadcast line in line 111 for errors, as the returned hash may contain the errro_description from AAD.:
if (requestInfo.parameters['access_token']) {
                                        _adal.callback(_adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION), requestInfo.parameters['access_token']);
                                        return;
                                    } else if (requestInfo.parameters['id_token']) {
                                        _adal.callback(_adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION), requestInfo.parameters['id_token']);
                                        return;
                                    } else {
                                        $rootScope.$broadcast('adal:loginFailure', _adal._getItem(_adal.CONSTANTS.STORAGE.ERROR_DESCRIPTION));
                                    }

File: package.json [hunk 6]
```diff
@@ -5,15 +5,10 @@
     "email": "msopentech@microsoft.com",
     "url": "https://github.com/AzureAD/azure-activedirectory-library-for-js"
```
Comment (polita) [inline package.json]: Should this still be published as MSOT, or should we switch it to Microsoft?

File: package.json (hunk 3 above)
Comment (polita) [inline package.json]: Please make sure it's updated in Readme.md

---
In reply to: [57949952](https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/253#discussion_r57949952) [](ancestors = 57949952)

Comment (tushargupta51) [inline package.json]: I had a local commit that updates other files, just pushed it out to github.

Comment (polita) [inline package.json]: Ah, yes, now I see the new iteration. Thanks.

---
In reply to: [58117639](https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/253#discussion_r58117639) [](ancestors = 58117639)

File: README.md [hunk 7]
```diff
@@ -7,7 +7,7 @@ This library is optimized for working together with AngularJS.
 
 ## The Library
 
-This is a GA released version. The current version is **1.0.8**.
+This is a GA released version. The current version is **1.0.9**.
```
Comment (polita) [inline README.md]: Do the paths below and the CDN version need to change for the new version?

File: lib/adal-angular.js (hunk 5 above)
Comment (tushargupta51) [inline lib/adal-angular.js]: @ischrei Thanks for catching this! I agree that we need to report the error somehow but the loginFailure event does not seem to be the right one to be broadcasted. This error is likely to occur at renew time rather than login. We are on a tight schedule to release 1.0.9, I will fix this up in next release. If this is not yet reported, please feel free to open an issue.

**Comment by tushargupta51** [comment]
@weijjia I talked with @brentschmaltz and @polita regarding the new broadcast events and we agreed on adding those events.

**Comment by weijjia** [comment]
@tushargupta51 Good to know, thanks for the info. :)

File: package.json (hunk 6 above)
Comment (tushargupta51) [inline package.json]: This should be switched to Microsoft. how about nugetaad@microsoft.com? Thats what we add in our wilson nuget packages. Now that we are using this email address for npm, makes sense to use that email address here too.

File: README.md [hunk 8]
```diff
@@ -7,17 +7,17 @@ This library is optimized for working together with AngularJS.
...
     <!-- Latest compiled and minified JavaScript -->
-    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.8/js/adal.min.js"></script>
-    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.8/js/adal-angular.min.js"></script>
+    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.9/js/adal.min.js"></script>
+    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.9/js/adal-angular.min.js"></script>
 
-CDN will be updated to latest version 1.0.8.
+CDN will be updated to latest version 1.0.9.
 
 Via Bower:
```
Comment (polita) [inline README.md]: We should have a new section here for "Via NPM"

Comment (tushargupta51) [inline README.md]: Added.
